namespace CustomText
{
    public enum Custom_ColorStyle
    {
        Default = 0,
        White = 1,
        Black = 2,
        PopUp_Background =3,
        PopUp_Text =4,
        PopUp_Button =5,
        PopUp_VotingBackground =6,
        PopUp_VotingSelected =7,
        MainMenu_ButtonShape =8,
        MainMenu_Text =9,
        MainMenu_InputExample =10,
        MainMenu_Field =11,
        ScaleSettings_Base =12,
        ScaleSettings_Filled =13,
        ScaleSettings_Button =14,
        NoBackground_StandardButton =15,
        NoBackground_SpecialButton =16,
        NoBackground_Text =17, 
        NoBackground_Currency = 18,
        LevelMenu_PassedBackground =19,
        LevelMenu_PassedText =20,
        LevelMenu_NotPassed =21,
        DifficultyMenu_ActiveDifficulty =22,
        DifficultyMenu_Base =23,
        ChooseCards_MainBackground =24,
        ChooseCards_Background =25,
        ChooseCards_Buttons =26,
        ChooseCards_ButtonsShapes =27,
        ChooseShapes_Background =28,
        ChooseShapes_Text =29,
        PagesLvl_ovney_Base =30,
        PagesLevels_Active = 31,
        PagesLevels_Number =32,
        PanelInGame_Contents =33,
        PanelInGame_Background =34,
        CustomLevels_Background =35,
        CustomLevels_Text = 36,
        CustomLevels_ButtonText =37,
        CustomLevels_ButtonFigure = 38,
        CustomLevels_AnglePassed = 39,
        CustomLevels_AngleNotPassed = 40,
        CustomLevels_H3 =41,
        LevelName_InputExample = 42,
        LevelName_Entered = 43,
        LevelName_Field = 44,
        BlackKing_Left = 45,
        BlackKing_Right = 46
    }
}